=== fudo4249/gps-map-demo/data/json/schema_station.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",

	"type": "array",

	"items" : {
		"type": "object",
		"properties": {
			"@id": {
				"type": "string"
			},
			"@type": {
				"type": "string"
			},
			"dc:date": {
				"type": "string"
			},
			"geo:lat": {
				"type": "number"
			},
			"@context": {
				"type": "string"
			},
			"dc:title": {
				"type": "string"
			},
			"geo:long": {
				"type": "number"
			},
			"owl:sameAs": {
				"type": "string"
			},
			"odpt:railway": {
				"type": "string"
			},
			"odpt:operator": {
				"type": "string"
			},
			"odpt:stationCode": {
				"type": "string"
			},

			"odpt:stationTitle": {
				"type": "object",
				"properties": {

					"en": { "type": "string" },
					"ja": { "type": "string" },
					"ko": { "type": "string" },
					"zh-Hans": { "type": "string" },
					"zh-Hant": { "type": "string" }
				}
			},

			"odpt:passengerSurvey": {
				"type": "array",
				"items": {
					"type": "string"
				}
			},
			"odpt:stationTimetable": {
				"type": "array",
				"items": {
					"type": "string"
				}
			},
			"odpt:connectingRailway": {
				"type": "array",
				"items": {
					"type": "string"
				}
			}
		}
	}

}

=== fudo4249/gps-map-demo/data/json/rinkai_station.json
[
	{
		"@id": "urn:ucode:_00001C00000000000001000003102B2E",
		"@type": "odpt:Station",
		"dc:date": "2021-06-21T14:00:00+09:00",
		"geo:lat": 35.63457,
		"@context": "http://vocab.odpt.org/context_odpt.jsonld",
		"dc:title": "国際展示場",
		"geo:long": 139.79163,
		"owl:sameAs": "odpt.Station:TWR.Rinkai.KokusaiTenjijo",
		"odpt:railway": "odpt.Railway:TWR.Rinkai",
		"odpt:operator": "odpt.Operator:TWR",
		"odpt:stationCode": "R3",
		"odpt:stationTitle": {
			"en": "Kokusai-tenjijo",
			"ja": "国際展示場",
			"ko": "국제전시장",
			"zh-Hans": "国际展示场",
			"zh-Hant": "國際展示場"
		},
		"odpt:passengerSurvey": [
			"odpt.PassengerSurvey:TWR.KokusaiTenjijo"
		],
		"odpt:stationTimetable": [
			"odpt.StationTimetable:TWR.Rinkai.KokusaiTenjijo.Inbound.Weekday",
			"odpt.StationTimetable:TWR.Rinkai.KokusaiTenjijo.Inbound.SaturdayHoliday",
			"odpt.StationTimetable:TWR.Rinkai.KokusaiTenjijo.Outbound.Weekday",
			"odpt.StationTimetable:TWR.Rinkai.KokusaiTenjijo.Outbound.SaturdayHoliday"
		],
		"odpt:connectingRailway": [
			"odpt.Railway:Yurikamome.Yurikamome"
		]
	},
	{
		"@id": "urn:ucode:_00001C00000000000001000003102B32",
		"@type": "odpt:Station",
		"dc:date": "2021-06-21T14:00:00+09:00",
		"geo:lat": 35.60741,
		"@context": "http://vocab.odpt.org/context_odpt.jsonld",
		"dc:title": "大井町",
		"geo:long": 139.73474,
		"owl:sameAs": "odpt.Station:TWR.Rinkai.Oimachi",
		"odpt:railway": "odpt.Railway:TWR.Rinkai",
		"odpt:operator": "odpt.Operator:TWR",
		"odpt:stationCode": "R7",
		"odpt:stationTitle": {
			"en": "Oimachi",
			"ja": "大井町",
			"ko": "오이마치",
			"zh-Hans": "大井町",
			"zh-Hant": "大井町"
		},
		"odpt:passengerSurvey": [
			"odpt.PassengerSurvey:TWR.Oimachi"
		],
		"odpt:stationTimetable": [
			"odpt.StationTimetable:TWR.Rinkai.Oimachi.Inbound.Weekday",
			"odpt.StationTimetable:TWR.Rinkai.Oimachi.Inbound.SaturdayHoliday",
			"odpt.StationTimetable:TWR.Rinkai.Oimachi.Outbound.Weekday",
			"odpt.StationTimetable:TWR.Rinkai.Oimachi.Outbound.SaturdayHoliday"
		],
		"odpt:connectingRailway": [
			"odpt.Railway:JR-East.KeihinTohokuNegishi",
			"odpt.Railway:Tokyu.Oimachi"
		]
	},
	{
		"@id": "urn:ucode:_00001C00000000000001000003102B33",
		"@type": "odpt:Station",
		"dc:date": "2021-06-21T14:00:00+09:00",
		"geo:lat": 35.62002,
		"@context": "http://vocab.odpt.org/context_odpt.jsonld",
		"dc:title": "大崎",
		"geo:long": 139.7282,
		"owl:sameAs": "odpt.Station:TWR.Rinkai.Osaki",
		"odpt:railway": "odpt.Railway:TWR.Rinkai",
		"odpt:operator": "odpt.Operator:TWR",
		"odpt:stationCode": "R8",
		"odpt:stationTitle": {
			"en": "Osaki",
			"ja": "大崎",
			"ko": "오사키",
			"zh-Hans": "大崎",
			"zh-Hant": "大崎"
		},
		"odpt:passengerSurvey": [
			"odpt.PassengerSurvey:TWR.Osaki"
		],
		"odpt:stationTimetable": [
			"odpt.StationTimetable:TWR.Rinkai.Osaki.Inbound.Weekday",
			"odpt.StationTimetable:TWR.Rinkai.Osaki.Inbound.SaturdayHoliday"
		],
		"odpt:connectingRailway": [
			"odpt.Railway:JR-East.SaikyoKawagoe",
			"odpt.Railway:JR-East.ShonanShinjuku",
			"odpt.Railway:JR-East.SotetsuDirect",
			"odpt.Railway:JR-East.Yamanote"
		]
	},
	{
		"@id": "urn:ucode:_00001C00000000000001000003102B2C",
		"@type": "odpt:Station",
		"dc:date": "2021-06-21T14:00:00+09:00",
		"geo:lat": 35.64604,
		"@context": "http://vocab.odpt.org/context_odpt.jsonld",
		"dc:title": "新木場",
		"geo:long": 139.82678,
		"owl:sameAs": "odpt.Station:TWR.Rinkai.ShinKiba",
		"odpt:railway": "odpt.Railway:TWR.Rinkai",
		"odpt:operator": "odpt.Operator:TWR",
		"odpt:stationCode": "R1",
		"odpt:stationTitle": {
			"en": "Shin-kiba",
			"ja": "新木場",
			"ko": "신키바",
			"zh-Hans": "新木场",
			"zh-Hant": "新木場"
		},
		"odpt:passengerSurvey": [
			"odpt.PassengerSurvey:TWR.ShinKiba"
		],
		"odpt:stationTimetable": [
			"odpt.StationTimetable:TWR.Rinkai.ShinKiba.Outbound.Weekday",
			"odpt.StationTimetable:TWR.Rinkai.ShinKiba.Outbound.SaturdayHoliday"
		],
		"odpt:connectingRailway": [
			"odpt.Railway:JR-East.Keiyo",
			"odpt.Railway:TokyoMetro.Yurakucho"
		]
	},
	{
		"@id": "urn:ucode:_00001C00000000000001000003102B31",
		"@type": "odpt:Station",
		"dc:date": "2021-06-21T14:00:00+09:00",
		"geo:lat": 35.60897,
		"@context": "http://vocab.odpt.org/context_odpt.jsonld",
		"dc:title": "品川シーサイド",
		"geo:long": 139.74967,
		"owl:sameAs": "odpt.Station:TWR.Rinkai.ShinagawaSeaside",
		"odpt:railway": "odpt.Railway:TWR.Rinkai",
		"odpt:operator": "odpt.Operator:TWR",
		"odpt:stationCode": "R6",
		"odpt:stationTitle": {
			"en": "Shinagawa Seaside",
			"ja": "品川シーサイド",
			"ko": "시나가와시사이드",
			"zh-Hans": "品川海滨",
			"zh-Hant": "品川海濱"
		},
		"odpt:passengerSurvey": [
			"odpt.PassengerSurvey:TWR.ShinagawaSeaside"
		],
		"odpt:stationTimetable": [
			"odpt.StationTimetable:TWR.Rinkai.ShinagawaSeaside.Inbound.Weekday",
			"odpt.StationTimetable:TWR.Rinkai.ShinagawaSeaside.Inbound.SaturdayHoliday",
			"odpt.StationTimetable:TWR.Rinkai.ShinagawaSeaside.Outbound.Weekday",
			"odpt.StationTimetable:TWR.Rinkai.ShinagawaSeaside.Outbound.SaturdayHoliday"
		]
	},
	{
		"@id": "urn:ucode:_00001C00000000000001000003102B2D",
		"@type": "odpt:Station",
		"dc:date": "2021-06-21T14:00:00+09:00",
		"geo:lat": 35.6406,
		"@context": "http://vocab.odpt.org/context_odpt.jsonld",
		"dc:title": "東雲",
		"geo:long": 139.80328,
		"owl:sameAs": "odpt.Station:TWR.Rinkai.Shinonome",
		"odpt:railway": "odpt.Railway:TWR.Rinkai",
		"odpt:operator": "odpt.Operator:TWR",
		"odpt:stationCode": "R2",
		"odpt:stationTitle": {
			"en": "Shinonome",
			"ja": "東雲",
			"ko": "시노노메",
			"zh-Hans": "东云",
			"zh-Hant": "東雲"
		},
		"odpt:passengerSurvey": [
			"odpt.PassengerSurvey:TWR.Shinonome"
		],
		"odpt:stationTimetable": [
			"odpt.StationTimetable:TWR.Rinkai.Shinonome.Inbound.Weekday",
			"odpt.StationTimetable:TWR.Rinkai.Shinonome.Inbound.SaturdayHoliday",
			"odpt.StationTimetable:TWR.Rinkai.Shinonome.Outbound.Weekday",
			"odpt.StationTimetable:TWR.Rinkai.Shinonome.Outbound.SaturdayHoliday"
		]
	},
	{
		"@id": "urn:ucode:_00001C00000000000001000003102B30",
		"@type": "odpt:Station",
		"dc:date": "2021-06-21T14:00:00+09:00",
		"geo:lat": 35.62038,
		"@context": "http://vocab.odpt.org/context_odpt.jsonld",
		"dc:title": "天王洲アイル",
		"geo:long": 139.75084,
		"owl:sameAs": "odpt.Station:TWR.Rinkai.TennozuIsle",
		"odpt:railway": "odpt.Railway:TWR.Rinkai",
		"odpt:operator": "odpt.Operator:TWR",
		"odpt:stationCode": "R5",
		"odpt:stationTitle": {
			"en": "Tennozu Isle",
			"ja": "天王洲アイル",
			"ko": "덴노즈아일",
			"zh-Hans": "天王洲岛",
			"zh-Hant": "天王洲島"
		},
		"odpt:passengerSurvey": [
			"odpt.PassengerSurvey:TWR.TennozuIsle"
		],
		"odpt:stationTimetable": [
			"odpt.StationTimetable:TWR.Rinkai.TennozuIsle.Inbound.Weekday",
			"odpt.StationTimetable:TWR.Rinkai.TennozuIsle.Inbound.SaturdayHoliday",
			"odpt.StationTimetable:TWR.Rinkai.TennozuIsle.Outbound.Weekday",
			"odpt.StationTimetable:TWR.Rinkai.TennozuIsle.Outbound.SaturdayHoliday"
		],
		"odpt:connectingRailway": [
			"odpt.Railway:TokyoMonorail.HanedaAirport"
		]
	},
	{
		"@id": "urn:ucode:_00001C00000000000001000003102B2F",
		"@type": "odpt:Station",
		"dc:date": "2021-06-21T14:00:00+09:00",
		"geo:lat": 35.62754,
		"@context": "http://vocab.odpt.org/context_odpt.jsonld",
		"dc:title": "東京テレポート",
		"geo:long": 139.77885,
		"owl:sameAs": "odpt.Station:TWR.Rinkai.TokyoTeleport",
		"odpt:railway": "odpt.Railway:TWR.Rinkai",
		"odpt:operator": "odpt.Operator:TWR",
		"odpt:stationCode": "R4",
		"odpt:stationTitle": {
			"en": "Tokyo Teleport",
			"ja": "東京テレポート",
			"ko": "도쿄텔레포트",
			"zh-Hans": "东京电讯",
			"zh-Hant": "東京電訊"
		},
		"odpt:passengerSurvey": [
			"odpt.PassengerSurvey:TWR.TokyoTeleport"
		],
		"odpt:stationTimetable": [
			"odpt.StationTimetable:TWR.Rinkai.TokyoTeleport.Inbound.Weekday",
			"odpt.StationTimetable:TWR.Rinkai.TokyoTeleport.Inbound.SaturdayHoliday",
			"odpt.StationTimetable:TWR.Rinkai.TokyoTeleport.Outbound.Weekday",
			"odpt.StationTimetable:TWR.Rinkai.TokyoTeleport.Outbound.SaturdayHoliday"
		]
	}
]

=== fudo4249/gps-map-demo/data/json/rinkai_metro_station.json
[
	{
		"@id": "urn:ucode:_0000metro1",
		"@type": "odpt:Station",
		"dc:date": "2023-02-01T14:00:00+09:00",
		"geo:lat": 35.67998995203577,
		"geo:long": 139.76761832409147,
		"@context": "http://vocab.odpt.org/context_odpt.jsonld",
		"dc:title": "東京",
		"owl:sameAs": "odpt.Station:TWR.RinkaiMetro.Tokyo",
		"odpt:railway": "odpt.Railway:TWR.RinkaiMetro",
		"odpt:operator": "odpt.Operator:TWR",
		"odpt:stationCode": "RM1",
		"odpt:stationTitle": {
			"en": "Tokyo",
			"ja": "東京",
			"zh-Hans": "東京",
			"zh-Hant": "東京"
		},
		"odpt:stationTimetable": [
			"odpt.StationTimetable:TWR.RinkaiMetro.Tokyo.Inbound.Weekday",
			"odpt.StationTimetable:TWR.RinkaiMetro.Tokyo.Outbound.Weekday"
		],
		"odpt:connectingRailway": []
	},
	{
		"@id": "urn:ucode:_0000metro2",
		"@type": "odpt:Station",
		"dc:date": "2023-02-01T14:00:00+09:00",
		"geo:lat": 35.67498747811995,
		"geo:long": 139.76370087283587,
		"@context": "http://vocab.odpt.org/context_odpt.jsonld",
		"dc:title": "新銀座",
		"owl:sameAs": "odpt.Station:TWR.RinkaiMetro.Shinginza",
		"odpt:railway": "odpt.Railway:TWR.RinkaiMetro",
		"odpt:operator": "odpt.Operator:TWR",
		"odpt:stationCode": "RM2",
		"odpt:stationTitle": {
			"en": "Shinginza",
			"ja": "新銀座"
		},
		"odpt:stationTimetable": [],
		"odpt:connectingRailway": []
	},
	{
		"@id": "urn:ucode:_0000metro3",
		"@type": "odpt:Station",
		"dc:date": "2023-02-01T14:00:00+09:00",
		"geo:lat": 35.665778070081835,
		"geo:long": 139.76947982825013,
		"@context": "http://vocab.odpt.org/context_odpt.jsonld",
		"dc:title": "新築地",
		"owl:sameAs": "odpt.Station:TWR.RinkaiMetro.Shintsukiji",
		"odpt:railway": "odpt.Railway:TWR.RinkaiMetro",
		"odpt:operator": "odpt.Operator:TWR",
		"odpt:stationCode": "RM3",
		"odpt:stationTitle": {
			"en": "Shintsukiji",
			"ja": "新築地"
		},
		"odpt:stationTimetable": [],
		"odpt:connectingRailway": []
	},
	{
		"@id": "urn:ucode:_0000metro4",
		"@type": "odpt:Station",
		"dc:date": "2023-02-01T14:00:00+09:00",
		"geo:lat": 35.65939256639024,
		"geo:long": 139.77759442992416,
		"@context": "http://vocab.odpt.org/context_odpt.jsonld",
		"dc:title": "勝どき",
		"owl:sameAs": "odpt.Station:TWR.RinkaiMetro.Kachidoki",
		"odpt:railway": "odpt.Railway:TWR.RinkaiMetro",
		"odpt:operator": "odpt.Operator:TWR",
		"odpt:stationCode": "RM4",
		"odpt:stationTitle": {
			"en": "Kachidoki",
			"ja": "勝どき"
		},
		"odpt:stationTimetable": [],
		"odpt:connectingRailway": []
	},
	{
		"@id": "urn:ucode:_0000metro5",
		"@type": "odpt:Station",
		"dc:date": "2023-02-01T14:00:00+09:00",
		"geo:lat": 35.65598579905261,
		"geo:long": 139.78107046893876,
		"@context": "http://vocab.odpt.org/context_odpt.jsonld",
		"dc:title": "晴海",
		"owl:sameAs": "odpt.Station:TWR.RinkaiMetro.Harumi",
		"odpt:railway": "odpt.Railway:TWR.RinkaiMetro",
		"odpt:operator": "odpt.Operator:TWR",
		"odpt:stationCode": "RM5",
		"odpt:stationTitle": {
			"en": "Harumi",
			"ja": "晴海"
		},
		"odpt:stationTimetable": [],
		"odpt:connectingRailway": []
	},
	{
		"@id": "urn:ucode:_0000metro6",
		"@type": "odpt:Station",
		"dc:date": "2023-02-01T14:00:00+09:00",
		"geo:lat": 35.6449380691587,
		"geo:long": 139.78478190875546,
		"@context": "http://vocab.odpt.org/context_odpt.jsonld",
		"dc:title": "豊洲市場",
		"owl:sameAs": "odpt.Station:TWR.RinkaiMetro.ToyosuIchiba",
		"odpt:railway": "odpt.Railway:TWR.RinkaiMetro",
		"odpt:operator": "odpt.Operator:TWR",
		"odpt:stationCode": "RM6",
		"odpt:stationTitle": {
			"en": "ToyosuIchiba",
			"ja": "豊洲市場"
		},
		"odpt:stationTimetable": [],
		"odpt:connectingRailway": []
	},
	{
		"@id": "urn:ucode:_0000metro7",
		"@type": "odpt:Station",
		"dc:date": "2023-02-01T14:00:00+09:00",
		"geo:lat": 35.635227934253514,
		"geo:long": 139.79279399832322,
		"@context": "http://vocab.odpt.org/context_odpt.jsonld",
		"dc:title": "東京ビッグサイト",
		"owl:sameAs": "odpt.Station:TWR.RinkaiMetro.TokyoBigSight",
		"odpt:railway": "odpt.Railway:TWR.RinkaiMetro",
		"odpt:operator": "odpt.Operator:TWR",
		"odpt:stationCode": "RM7",
		"odpt:stationTitle": {
			"en": "TokyoBigSight",
			"ja": "東京ビッグサイト"
		},
		"odpt:stationTimetable": [],
		"odpt:connectingRailway": []
	}
]
